services:
  - type: web
    name: fastapi-backend
    env: python
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    plan: free
    region: oregon
    rootDir: backend

  - type: web    # ← changed from "static" to "web"
    name: react-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: build
    startCommand: ""  # no start command for static site
    rootDir: ccc
